# Generated by Django 5.2.6 on 2025-10-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('cita', 'Cita'), ('vacuna', 'Vacuna'), ('desparasitacion', 'Desparasitación'), ('medicamento', 'Medicamento'), ('emergencia', 'Emergencia'), ('sistema', 'Sistema')], default='general', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('enviada_por_email', models.BooleanField(default=False)),
                ('url_relacionada', models.URLField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita', 'Cita Programada'), ('vacuna', 'Vacuna Próxima'), ('desparasitacion', 'Desparasitación'), ('medicamento', 'Medicamento'), ('control', 'Control Médico'), ('cumpleanos', 'Cumpleaños Mascota')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_recordatorio', models.DateTimeField()),
                ('dias_anticipacion', models.PositiveIntegerField(default=1)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('objeto_relacionado_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_relacionado_tipo', models.CharField(blank=True, max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['fecha_recordatorio'],
            },
        ),
    ]
