# Generated by Django 5.2.6 on 2025-10-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad'),
        ),
    ]
