# Generated by Django 5.2.6 on 2025-10-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_foto_perfil'),
        ('notificaciones', '0002_notificacion_fecha_lectura_notificacion_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente'),
        ),
    ]
