# Generated by Django 5.2.6 on 2025-11-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notificacion_cliente'),
        ('veterinario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='veterinario.veterinario'),
        ),
    ]
