# Generated by Django 5.2.6 on 2025-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_notificacion_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='para_admin',
            field=models.BooleanField(default=False, verbose_name='Para Administrador'),
        ),
    ]
