databases:
  - name: veterinaria_db
    plan: free
    databaseName: veterinaria_db
    user: veterinaria_user

services:
  - type: web
    plan: free
    name: veterinaria-app
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd veterinaria_project && python -m gunicorn veterinaria_project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        value: postgresql://veterinaria_db_f9ru_user:MiMEsx8yHudgtuTgwzVl9JdteIyPeA5v@dpg-d424m0gdl3ps73ec6pjg-a.oregon-postgres.render.com/veterinaria_db_f9ru
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: veterinaria_project.settings.production
      - key: PYTHONPATH
        value: /opt/render/project/src/veterinaria_project
      - key: ALLOWED_HOSTS
        value: vet-love.onrender.com,veterinaria-app.onrender.com,localhost,127.0.0.1,0.0.0.0