# Generated by Django 5.2.6 on 2025-10-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_mascota',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('todos', 'Todos los tipos')], default='todos', max_length=20, verbose_name='Tipo de mascota'),
        ),
    ]
