# Generated by Django 5.2.6 on 2025-09-18 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_cliente_direccion_and_more'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmedico',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial Médico', 'verbose_name_plural': 'Historiales Médicos'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['nombre'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'ordering': ['-fecha_aplicacion'], 'verbose_name': 'Vacuna', 'verbose_name_plural': 'Vacunas'},
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='diagnostico',
            field=models.TextField(verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='mascotas.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='tratamiento',
            field=models.TextField(blank=True, verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='veterinario',
            field=models.CharField(max_length=100, verbose_name='Veterinario'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='caracteristicas',
            field=models.TextField(blank=True, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=100, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('otro', 'Otro')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='aplicada',
            field=models.BooleanField(default=True, verbose_name='Aplicada'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha_aplicacion',
            field=models.DateField(verbose_name='Fecha de aplicación'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha_proxima',
            field=models.DateField(verbose_name='Próxima aplicación'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='mascotas.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
