# Generated by Django 5.2.6 on 2025-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_historialmedico_options_alter_mascota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='condicion_corporal',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Muy delgado'), (2, '2 - Delgado'), (3, '3 - Ideal'), (4, '4 - Sobrepeso'), (5, '5 - Obeso')], null=True, verbose_name='Condición corporal'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='motivo_consulta',
            field=models.TextField(default='Consulta general', verbose_name='Motivo de la consulta'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='proxima_cita',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima cita'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='vacunas_aplicadas',
            field=models.TextField(blank=True, verbose_name='Vacunas aplicadas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='alergias_conocidas',
            field=models.TextField(blank=True, verbose_name='Alergias conocidas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='cartilla_vacunacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Estado de vacunación'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color principal'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='comportamiento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comportamiento'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, verbose_name='Enfermedades crónicas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('desconocido', 'Desconocido')], default='desconocido', max_length=15, verbose_name='Esterilizado'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_esterilizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de esterilización'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='frecuencia_alimentacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Frecuencia de alimentación'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='microchip',
            field=models.CharField(blank=True, max_length=15, verbose_name='Microchip'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='observaciones_comportamiento',
            field=models.TextField(blank=True, verbose_name='Observaciones de comportamiento'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='permite_manejo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Permitividad al manejo'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_alimentacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de alimentación'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='laboratorio',
            field=models.CharField(default='Laboratorio no especificado', max_length=100, verbose_name='Laboratorio fabricante'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='lote',
            field=models.CharField(default='Lote no especificado', max_length=20, verbose_name='Número de lote'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='reacciones_adversas',
            field=models.TextField(blank=True, verbose_name='Reacciones adversas'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='sitio_aplicacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sitio de aplicación'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='via_aplicacion',
            field=models.CharField(choices=[('subcutanea', 'Subcutánea'), ('intramuscular', 'Intramuscular'), ('intranasal', 'Intranasal')], default='subcutanea', max_length=15, verbose_name='Vía de aplicación'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='tratamiento',
            field=models.TextField(verbose_name='Tratamiento prescrito'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='caracteristicas',
            field=models.TextField(blank=True, verbose_name='Señas particulares'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('otro', 'Otro')], max_length=10, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la vacuna'),
        ),
    ]
