# Generated by Django 5.2.6 on 2025-10-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_historialmedico_condicion_corporal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='alergias_tipo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipos de alergias'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='cirugias_previas',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cirugías previas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='comportamiento_consulta',
            field=models.CharField(choices=[('tranquilo', 'Tranquilo y Cooperativo'), ('nervioso', 'Nervioso pero Manejable'), ('asustadizo', 'Muy Asustadizo/Difícil de Examinar'), ('agresivo', 'Puede ser Agresivo/Morder'), ('solo_dueno', 'Solo Permite Manejo del Dueño'), ('requiere_sedacion', 'Requiere Sedación para Procedimientos')], default='tranquilo', max_length=20, verbose_name='Comportamiento en consulta'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='desparasitacion',
            field=models.CharField(choices=[('actualizado', 'Desparasitación Actualizada'), ('pendiente', 'Desparasitación Pendiente'), ('desconocido', 'Estado Desconocido')], default='desconocido', max_length=20, verbose_name='Estado de desparasitación'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='enfermedades_tipo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipos de enfermedades'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado_vacunacion',
            field=models.CharField(choices=[('completo', 'Vacunación Completa y Actualizada'), ('parcial', 'Algunas Vacunas Pendientes'), ('desconocido', 'Desconocido/No hay Registros'), ('ninguna', 'Sin Vacunación')], default='desconocido', max_length=20, verbose_name='Estado de vacunación'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_ultima_cirugia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha última cirugía'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_ultima_desparasitacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha última desparasitación'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_ultima_vacuna',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha última vacuna'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='medicacion_actual',
            field=models.TextField(blank=True, verbose_name='Medicación actual'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='peso_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso actual (kg)'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono emergencia'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='veterinario_habitual',
            field=models.CharField(blank=True, max_length=200, verbose_name='Veterinario habitual'),
        ),
    ]
