# Generated by Django 5.2.6 on 2025-11-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_alergias_tipo_mascota_cirugias_previas_and_more'),
        ('veterinario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='veterinario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_asignadas', to='veterinario.veterinario', verbose_name='Veterinario Asignado'),
        ),
    ]
