# Generated by Django 5.2.6 on 2025-09-17 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta General'), ('vacunacion', 'Vacunación'), ('urgencia', 'Urgencia'), ('cirugia', 'Cirugía'), ('estetica', 'Estética')], max_length=20)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
