# Generated by Django 5.2.6 on 2025-09-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(verbose_name='Motivo de la Consulta'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio Enviado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta General'), ('vacunacion', 'Vacunación'), ('urgencia', 'Urgencia'), ('cirugia', 'Cirugía'), ('estetica', 'Estética')], max_length=20, verbose_name='Tipo de Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Veterinario'),
        ),
    ]
