# Generated by Django 5.2.6 on 2025-10-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_options_alter_cita_estado_and_more'),
        ('mascotas', '0002_alter_historialmedico_options_alter_mascota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='alergias',
            field=models.TextField(blank=True, verbose_name='Alergias Conocidas'),
        ),
        migrations.AddField(
            model_name='cita',
            name='antecedentes',
            field=models.TextField(blank=True, verbose_name='Antecedentes Relevantes'),
        ),
        migrations.AddField(
            model_name='cita',
            name='confirmada_por_cliente',
            field=models.BooleanField(default=False, verbose_name='Confirmada por Cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='duracion_estimada',
            field=models.PositiveIntegerField(default=30, verbose_name='Duración Estimada (minutos)'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medicamentos_actuales',
            field=models.TextField(blank=True, verbose_name='Medicamentos Actuales'),
        ),
        migrations.AddField(
            model_name='cita',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('emergencia', 'Emergencia')], default='normal', max_length=15, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sala',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sala/Consultorio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sintomas',
            field=models.TextField(blank=True, verbose_name='Síntomas Presentados'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('consulta_general', 'Consulta General'), ('vacunacion', 'Vacunación'), ('desparasitacion', 'Desparasitación'), ('urgencia', 'Urgencia'), ('cirugia', 'Cirugía'), ('estetica', 'Estética/Baño'), ('odontologia', 'Odontología'), ('analisis', 'Análisis Clínicos'), ('radiologia', 'Radiología'), ('ecografia', 'Ecografía'), ('control', 'Control de Peso'), ('comportamiento', 'Consulta de Comportamiento'), ('nutricion', 'Consulta Nutricional')], max_length=20, verbose_name='Tipo de Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Veterinario Asignado'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'estado'], name='citas_cita_fecha_546979_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['mascota', 'fecha'], name='citas_cita_mascota_b5d6d6_idx'),
        ),
    ]
