# Generated by Django 5.2.6 on 2025-11-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_alergias_cita_antecedentes_and_more'),
        ('veterinario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='veterinario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='veterinario.veterinario', verbose_name='Veterinario Asignado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Veterinario Asignado (Texto)'),
        ),
    ]
