# Generated by Django 5.2.6 on 2025-09-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='clientes/fotos_perfil/default.png', null=True, upload_to='clientes/fotos_perfil/', verbose_name='Foto de perfil'),
        ),
    ]
